// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRXNhyLGyQ0ZoVYypBv_xiebjskJ7AbQE',
    appId: '1:690348411436:web:390527ab8b5082cc135f89',
    messagingSenderId: '690348411436',
    projectId: 'insta-clone-331b1',
    authDomain: 'insta-clone-331b1.firebaseapp.com',
    storageBucket: 'insta-clone-331b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKIAOR-IhzY3P938qoPjNxBaHCl3urRfk',
    appId: '1:690348411436:android:0b791d76af52c90c135f89',
    messagingSenderId: '690348411436',
    projectId: 'insta-clone-331b1',
    storageBucket: 'insta-clone-331b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4VRbx9TzP4t7dYZq9B1xkHHczgsEevPE',
    appId: '1:690348411436:ios:9056bf8b9455b18a135f89',
    messagingSenderId: '690348411436',
    projectId: 'insta-clone-331b1',
    storageBucket: 'insta-clone-331b1.appspot.com',
    iosClientId: '690348411436-lnkat3kvq52hhudqgvcehva3bq30ftmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4VRbx9TzP4t7dYZq9B1xkHHczgsEevPE',
    appId: '1:690348411436:ios:9056bf8b9455b18a135f89',
    messagingSenderId: '690348411436',
    projectId: 'insta-clone-331b1',
    storageBucket: 'insta-clone-331b1.appspot.com',
    iosClientId: '690348411436-lnkat3kvq52hhudqgvcehva3bq30ftmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
